name             'vagrant-ubuntu-lxc'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures vagrant-ubuntu-lxc'
long_description 'Installs/Configures vagrant-ubuntu-lxc'
version          '0.1.0'

depends 'yum', '>= 3.0'
depends 'apt'
